### ISSUE TITLE
Docker Compatibility?

### ISSUE THREAD

**Issue by aliadnani** [aliyun/kafka-connect-oss#2]
Hi, I just wanted to know how to make this compatible with docker?

I've loaded the compiled .jar file correctly, but it seems the docker Kafka connect instance cannot access core-site.xml properly.

I think this because I get this error most likely caused by the instance not being able to read the `fs.oss.impl` property:

```
[2020-06-10 04:00:11,573] ERROR WorkerSinkTask{id=oss-sink-1} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
	at com.aliyun.oss.connect.kafka.OSSSinkTask.start(OSSSinkTask.java:112)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:305)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:55)
	at com.aliyun.oss.connect.kafka.OSSSinkTask.start(OSSSinkTask.java:104)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:50)
	... 10 more
Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "oss"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3281)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at com.aliyun.oss.connect.kafka.storage.OSSStorage.<init>(OSSStorage.java:50)
	... 15 more
```

Thanks!

**Comment by aliadnani** [comment]
Got it working!

My files look like this

`Dockerfile`

```
FROM confluentinc/cp-kafka-connect-base
COPY core-site.xml /etc/core-site.xml
COPY core-site.xml $KAFKA_HOME/config/core-site.xml
COPY kafka-connect-oss-5.2.0.jar /usr/share/java/kafka-connect-oss/
COPY kafka-connect-oss-5.2.0.jar $KAFKA_HOME/libs/kafka-connect-oss/
```

`docker-compose.yaml`

```
connect:
    image: confluentinc/cp-kafka-connect-base:5.4.0
    hostname: connect
    container_name: connect
    build:
      context: .
      dockerfile: Dockerfile-oss
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      CLASSPATH: $CLASSPATH:$base_dir/config
```

**Comment by luthfianto** [comment]
@aliadnani hi, thank you for your guide. I able to copy the jar and core-site.xml succesfully.

However I want to ask about how do you put the compiled proto class into the docker, because I have this error: 

```Caused by: java.lang.ClassNotFoundException: com.aliyun.oss.connect.kafka.format.parquet.Parquet$Demo```

**Update:**

```
    "oss.parquet.protobuf.schema.class": "test,com.aliyun.oss.connect.kafka.format.parquet.Parquet$TestMessage",
```

will success

**Comment by aliadnani** [comment]
@rilut Ah I see. I was using JSON so I didn't come across this issue. 

Good to see that you managed to solve it. I'm not too familiar with Java but it seems that `com.aliyun.oss.connect.kafka.format.parquet.Parquet$TestMessage` is just an example class that's part of the tests, I think the docs gives you instructions on how to write your own class for your schema.
